### ISSUE TITLE
How to add to Opera GX. 

### ISSUE THREAD

**Issue by BoomBoomMushroom** [MoPaMo/treasurehunter#1]
Tutorial on how to install on Opera GX (and probably works on Chrome too)
1) Go to the firefox store for the extention (https://addons.mozilla.org/en-US/firefox/addon/treasurehunter/)
2) Click Download file (https://addons.mozilla.org/firefox/downloads/file/4382960/treasurehunter-1.1.xpi)
3) Change the .xpi extention into a .zip
4) Unzip the zip file
5) Open the folder (treasurehunter-1.1 or something like that)
6) Open the manifest.json and get ready to edit it.
7) Change ```"manifest_version": 2,``` to ```"manifest_version": 3,```
8) Remove this piece of code
`
  "browser_specific_settings": {
    "gecko": {
      "id": "{27213d4f-aab2-45ec-bf45-61449969b5b6}"
    }
  }
`

9) at the end your manifest.json should look like this:
`
{
  "manifest_version": 3,
  "name": "HighSeas Shop Favourite Button",
  "version": "1.1",
  "description": "Adds a favourite button to the HighSeas Shop items.",
  "permissions": [
    "storage",
    "activeTab"
  ],
  "content_scripts": [
    {
      "matches": [
        "https://highseas.hackclub.com/*"
      ],
      "js": [
        "content.js"
      ]
    }
  ]
}
`

10) Save the manifest.json and close it
11) In Opera go to extentions and click "Load Unpacked"
12) Select the folder (again probably treasurehunter-1.1 or something like that)
13) Tada you're done!!!

**Comment by MoPaMo** [comment]
If you want you can PR this into the Readme!

**Comment by BoomBoomMushroom** [comment]
Cool, i just opened a PR
